### ISSUE TITLE
Download big images crash

### ISSUE THREAD

**Issue by gdolle** [MSO4SC/MSOOrchestrator#2]
@emepetres @victorsndvg I put here the problem with sregistry download.
Currently, the bootstrap step randomly stops download for big images > 2go.

Sometimes it works, but most of the time the download is incomplete.
I "think" it's not related to ssh timeout. 

- I tried ssh command by hand several times and it works.
- I tried the bootstrap by hand it works

So I guess it's related to the orchestrator, something is happening during the bootstrap that kill the command. 

Any idea ?

I put new apps (very simple) on the marketplace so you can test.

**Comment by gdolle** [comment]
Most of the time it hangs around 33% ~ 40% of the download (~2go)

**Comment by gdolle** [comment]
@emepetres I think it might still be related to a timeout somewhere in the orchestrator during the bootstrap step or a signal that kill the command process. 
If it's caused ssh, maybe it comes from the orchestrator user ssh config ? In my case, if I rerun the bootstrap via ssh, I have no problems.

**Comment by emepetres** [comment]
Issue moved to [MSO4SC/cloudify-hpc-plugin #65](https://github.com/MSO4SC/cloudify-hpc-plugin/issues/65) via [**ZenHub**](https://www.zenhub.com/)
